import './globals.css'
import Navbar from '../components/Navbar'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      </head>
      <body>
        <Navbar />
        {children}
        <div className="background-elements">
          <img src="/medias/hechoEnZeratype.svg" alt="Hecho en Zeratype" className="hecho-en-zeratype" />
          <p className="zeratype-quote">
            En Zeratype <strong>conectamos</strong> marcas, creadores y audiencias para construir comunidades auténticas y conversaciones relevantes.
          </p>
        </div>
      </body>
    </html>
  )
}
