import './globals.css'
import Navbar from '../components/Navbar'
import LenisProvider from '../components/LenisProvider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
      </head>
      <body>
        <LenisProvider />
        <Navbar />
        {children}
        <div className="background-elements">
          <img src="/medias/hechoEnZeratype.svg" alt="Hecho en Zeratype" className="hecho-en-zeratype" />
        </div>
      </body>
    </html>
  )
}
